
FROM ubuntu:14.04

RUN apt-get update
RUN apt-get install -y python3
RUN apt-get install -y python3-pip
RUN apt-get install -y curl
RUN apt-get install -y ssh
RUN apt-get clean all
RUN pip3 install flask



